# Generated by Django 5.0.1 on 2024-01-24 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_actualisation', models.DateTimeField(auto_now=True)),
                ('date_suppression', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeFichier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('extension', models.CharField(max_length=16, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_actualisation', models.DateTimeField(auto_now=True)),
                ('date_suppression', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Objet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_actualisation', models.DateTimeField(auto_now=True)),
                ('date_suppression', models.DateTimeField(blank=True, null=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='WorkPage.classe')),
            ],
        ),
        migrations.CreateModel(
            name='Fichier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('fichier', models.FileField(upload_to='objets')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_actualisation', models.DateTimeField(auto_now=True)),
                ('date_suppression', models.DateTimeField(blank=True, null=True)),
                ('objet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WorkPage.objet')),
                ('type_fichier', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='WorkPage.typefichier')),
            ],
        ),
    ]
