# Generated by Django 5.0.1 on 2024-01-25 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkPage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objet',
            name='classe',
        ),
        migrations.RenameModel(
            old_name='Classe',
            new_name='Categorie',
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('fichier', models.FileField(upload_to='objets')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_actualisation', models.DateTimeField(auto_now=True)),
                ('date_suppression', models.DateTimeField(blank=True, null=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='WorkPage.categorie')),
            ],
        ),
        migrations.DeleteModel(
            name='Fichier',
        ),
        migrations.DeleteModel(
            name='TypeFichier',
        ),
        migrations.DeleteModel(
            name='Objet',
        ),
    ]
