# Generated by Django 5.0.1 on 2024-01-25 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkPage', '0002_remove_objet_classe_rename_classe_categorie_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='WorkPage.categorie'),
        ),
    ]
