# Generated by Django 5.0.1 on 2024-01-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkPage', '0003_alter_item_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='fichier',
            field=models.FileField(upload_to='items/'),
        ),
    ]
