# Generated by Django 5.0.1 on 2024-01-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkPage', '0003_alter_item_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='hauteur_bbox',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='item',
            name='largeur_bbox',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='item',
            name='longueur_bbox',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='item',
            name='nombre_aretes',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AddField(
            model_name='item',
            name='nombre_faces',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AddField(
            model_name='item',
            name='nombre_sommets',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AddField(
            model_name='item',
            name='surface',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='item',
            name='volume',
            field=models.FloatField(default=0.0),
        ),
    ]
