# Generated by Django 5.0.1 on 2024-01-26 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WorkPage', '0004_alter_item_fichier'),
        ('WorkPage', '0004_item_hauteur_bbox_item_largeur_bbox_and_more'),
    ]

    operations = [
    ]
