# Generated by Django 5.0.1 on 2024-01-27 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WorkPage", "0005_merge_20240126_1543"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="categorie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="WorkPage.categorie",
            ),
        ),
    ]
