# Generated by Django 5.0.1 on 2024-01-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WorkPage", "0006_alter_item_categorie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="fichier",
            field=models.FileField(blank=True, null=True, upload_to="items/"),
        ),
        migrations.AlterField(
            model_name="item",
            name="hauteur_bbox",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="largeur_bbox",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="longueur_bbox",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="nombre_aretes",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="nombre_faces",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="nombre_sommets",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="surface",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="volume",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
