# Generated by Django 5.0.1 on 2024-01-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WorkPage", "0007_alter_item_fichier_alter_item_hauteur_bbox_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="fichier",
            field=models.FileField(
                blank=True, null=True, unique=True, upload_to="items/"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="nom",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
