# Generated by Django 5.0.1 on 2024-01-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkPage', '0009_historique'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='fichier_stl_needs_update',
            field=models.BooleanField(default=False),
        ),
    ]
