# Generated by Django 5.0.1 on 2024-02-01 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkPage', '0010_item_fichier_stl_needs_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusteringParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_clusterisation', models.IntegerField(choices=[(1, 'DBSCAN'), (2, 'Propagation'), (3, 'K-Means')], default=3)),
                ('epsilon', models.FloatField(default=0.1)),
                ('echantillon_min', models.IntegerField(default=2)),
                ('num_clusters', models.IntegerField(default=3)),
            ],
        ),
    ]
